name: CI

on:
  push:
    branches:
      - main  # 或者您使用的其他主分支
  pull_request:
    branches:
      - main  # 同样适用于您使用的其他主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 根据需要设置 Node.js 的版本

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npx prettier --check .

    - name: Run ESLint
      run: npx eslint .

    - name: Run tests
      run: npm test
